# **Loops In Python**
###### Lops are used to repeat ceration statements
###### loops are certain statements that are continous repeted untill some condition is not true 


In [16]:
i = 5 
while i <= 5 :
    print("Data Science")
    i = i+1

Data Science


In [18]:
i = 5 
while i <=5 :
    print("Data Science")
    i = i+1

Data Science


In [20]:
i = 5 
while i <= 5 :
    print("This is Full  Stack Data Scienece Courses ")
    i = i+1
    

This is Full  Stack Data Scienece Courses 


In [5]:
i = 1
while i <= 5 :
    print("Data Science",i)
    i = i+1

Data Science 1
Data Science 2
Data Science 3
Data Science 4
Data Science 5


In [3]:
i = 1         # initializing
while i<=5:    # condition
    print('data science : ', i)
    i = i + 1  # increment

data science :  1
data science :  2
data science :  3
data science :  4
data science :  5


# Foor Loop 

In [8]:
name  = 'nit'
for i in name:
    print(i)

n
i
t


In [10]:
name1 = [1,2,5,'Hello']
for i in name1 :
    print(i)
    

1
2
5
Hello


In [12]:
for i in [2, 3, 7.8, 'hi']:
    print(i)

2
3
7.8
hi


In [14]:
range(5)

range(0, 5)

In [16]:
for i in range(5):
    print(i)

0
1
2
3
4


In [20]:
for i in range(5,20):
    print(i)

5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [22]:
for i in range(5,20,3):
    print(i)

5
8
11
14
17


In [24]:
# print the value which is divisible by 5 
for i in range(1,51):
    if i %5  == 0:
     print(i)

5
10
15
20
25
30
35
40
45
50


In [49]:
# print the no which is not divisble b 5
print("The no which is not dicvible by 5 are ")
for i in range(1,51):
    if i%5 != 0 :
         
           print(i, end=" ")

The no which is not dicvible by 5 are 
1 2 3 4 6 7 8 9 11 12 13 14 16 17 18 19 21 22 23 24 26 27 28 29 31 32 33 34 36 37 38 39 41 42 43 44 46 47 48 49 

Lets discuss more about 3 Keywords in deatils ---- Break || Continue || Pass 
BREAK STATEMNT - if you apply break statment in a loop then it will end the loop
Pass = skips block of code( function, class etc)
 Continue= skips 1 step/iteration during loop 
 Break= jumps out of the function/loop

In [57]:
available_choclet = 5 # the machine has only 10 candis 
x = int(input('How many choclets user want:?'))
i = 1
while i<=x:    
    if i>available_choclet: # we stop the execution but which code execution not entire code , i want to come out of while loop 
        break # break is statement | means jump out of the loop
    print('choclet')
    i += 1       
print('bye for now')

How many choclets user want:? 10


choclet
choclet
choclet
choclet
choclet
bye for now


In [ ]:
available_choclet = 5 # the machine has only 10 candis 
x = int(input('How many choclets user want:?'))
i = 1
while i<=x:    
    if i>available_choclet: # we stop the execution but which code execution not entire code , i want to come out of while loop 
        break # break is statement | means jump out of the loop
    print('choclet')
    i += 1       
print('bye for now')

In [65]:
print("keshav")

keshav


In [83]:
for i in range(1,11):
    if i == 5:
        break
    print(i)

1
2
3
4


In [117]:
for i in range(10,20):
    if i == 15 :
        continue
    print(i,end="  ")

10  11  12  13  14  16  17  18  19  

In [119]:
for i in range(1,11):
    if i == 6:
        continue
    print("hello",i)

hello 1
hello 2
hello 3
hello 4
hello 5
hello 7
hello 8
hello 9
hello 10


In [123]:
for i in range(1,51):
    if i%3 == 0 or i%5 == 0 :
        continue 
    print(i)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49


In [125]:
for i in range(1,51):
    if i%3 == 0 or i%5 == 0:
        continue 
    print(i, end=' ')

1 2 4 7 8 11 13 14 16 17 19 22 23 26 28 29 31 32 34 37 38 41 43 44 46 47 49 

In [131]:
for i in range (1,51):
    if (i%2 == 0):
        continue
    else :
        print(i)
print("Bye")

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
Bye


In [133]:
# Printing patterns

In [147]:
print('# # # # # # # #')
print('# # # # # # # #')
print('# # # # # # # ')
print('# # # # # # ')
print('# # # # # ')
print('# # # # ')
print('# # # ')

# # # # # # # #
# # # # # # # #
# # # # # # # 
# # # # # # 
# # # # # 
# # # # 
# # # 


In [153]:
for i in range(1,5):
    if i <= 5:
        print("####")

####
####
####
####


In [155]:
for j in range (4):
    print("####")

####
####
####
####


In [159]:
for j in range(4):
    print("#",end='')
print()

for j in range(4):
    print('#',end='')

####
####

In [167]:
for  j in range(10):
    print('#',end='')
print()
for j in range(8):
    print('#',end='')

##########
########

In [169]:

for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

print()

for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  

In [179]:
for  j in range(6):
    print('#',end="  ")
print()
for  j in range(6):
    print('#',end="  ")
print()
for  j in range(6):
    print('#',end="  ")
print()

#  #  #  #  #  #  
#  #  #  #  #  #  
#  #  #  #  #  #  


In [189]:
for i in range(4):
    for j in range(4):
        print("#",end=" ")
print()

# # # # # # # # # # # # # # # # 


In [191]:
for i in range(4):
    for j in range(i+1):
        print("#",end=" ")
    print()

# 
# # 
# # # 
# # # # 


In [197]:
for i in range(1,5):
    print("#"*i)

#
##
###
####


In [199]:
for i in range(4):
    for j in range(i+1):
        print('#', end="  ")
    print()

#  
#  #  
#  #  #  
#  #  #  #  


In [201]:
for i in range(1,5):
    print("#"*(5-i))

####
###
##
#


In [213]:
nums = [12,14,18,21,25,20]
for num in nums :
    if num%5 == 0 :
        print(num)
        break
        



25


In [215]:
nums = [12,14,18,21,25,20]
for num in nums :
    if num%5 == 0 :
        print(num)
        continue



25
20


In [221]:
num = 13 
for i in range(2,num):
    if num%i == 0 :
        print("Not a prime Number")
        break
else :
    print(" Prime Number")
    

 Prime Number


<img src="E:\image\Godshiva.jpg" alt="My Image" width="500">


## Arrays 


In [245]:
 from array import *
arr = array('i',[])
n = int(input("Enter the lenght of Array "))
for i in range(5):
    x = int(input("Enter the Next Value "))
    arr.append(x)
print(arr)

Enter the lenght of Array  2
Enter the Next Value  5
Enter the Next Value  5
Enter the Next Value  5
Enter the Next Value  3
Enter the Next Value  8


array('i', [5, 5, 5, 3, 8])


In [247]:
import numpy as np


In [251]:
from numpy import*
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [255]:
print(arr.dtype)

int32


In [259]:
arr = array([1,2,3,4,5.9])
print(arr)


[1.  2.  3.  4.  5.9]


In [261]:
print(arr.dtype)

float64


In [263]:
arr2 = array([1,2,3,4,5.9],float)
print(arr2)


[1.  2.  3.  4.  5.9]


In [265]:
arr.dtype

dtype('float64')

In [267]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [269]:
arr3.dtype

dtype('int32')