In [1]:
import numpy as np
x = [1,2,3,4,5]
print(np.array(x)) # way to creat a array 

[1 2 3 4 5]


In [23]:
a = [2,4,7,80,5]
arr = np.array(a)
#arr
print(arr.ndim)

1


In [19]:
l = []
for i in range(1,5) :
    int_1 = int(input("Enter a number:"))
    l.append(int_1)
print(np.array(l))

Enter a number: 12
Enter a number: 14
Enter a number: 13
Enter a number: 15


[12 14 13 15]


### checking the dimesnion of array 

In [28]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
ar2
print(ar2.ndim)

2


In [48]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4]]]) # when we create an nested array pass the args at  same 
ar3 
print(ar3.ndim)

AttributeError: 'numpy.ndarray' object has no attribute 'ndmin'

In [58]:
# 10 D array 
import numpy as np 
arr4 = np.array([1,2,3,34],ndmin = 10)
arr4
type(arr4)

numpy.ndarray

### Special Numpy Array 

### **Arrays Filled with zeros **

In [86]:
#np.zeros(1) One way of printing 
ar_zero = np.zeros(10) # ---> One dimensinal arrays 
print(ar_zero)
ar_zero = np.zeros((11,20))
print()
print(ar_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [90]:
np.zeros(3) # another way of priting by direct calling 


array([0., 0., 0.])

### **Array filled with ones**

In [100]:
arr_one = np.ones(5) # one dimesnional array filled with  1 
arr_one
np.ones(45) # another way of printing 
print()


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [102]:
arr_one1 = np.ones((7,8)) # two dimensional array 
arr_one1

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

### create an empty array 

In [105]:
np.empty(3)

array([0., 0., 0.])

### **arange**

In [116]:
np.arange((8))


array([0, 1, 2, 3, 4, 5, 6, 7])

In [118]:
arange = np.arange(10)
arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### diagonal array  (eye)

In [137]:
diag = np.eye(3)
diag

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
diag = np.eye(3,5)  # print 3 rows and 5 columns 
diag

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

### linspace 

In [142]:
linspace = np.linspace(0,20 , num = 5)
linspace

array([ 0.,  5., 10., 15., 20.])

### Create Numpy array with Random Numbers** 

In [161]:
rand = np.random.rand(4,3)
rand

array([[0.03567115, 0.54525928, 0.83154224],
       [0.16696244, 0.1772361 , 0.70922096],
       [0.63574889, 0.56744188, 0.74266023],
       [0.32747355, 0.44995336, 0.46157567]])

In [191]:
# randn 
randn = np.random.randn(6,4) #(we can pass arguments 1 is number of rows and second is the number of column )
randn 
#we can also try like this 
#np.random.randn(6)


array([[ 0.22613809,  0.69882136, -0.74058329, -0.77489103],
       [-1.34989308, -0.86222716,  1.70231529, -0.70666651],
       [ 0.76335829, -0.35561677, -0.78785298,  0.56124418],
       [-1.53291418, -0.31613549,  0.54808716, -1.09530758],
       [ 0.02278887,  0.07454579, -0.28417319,  0.25536574],
       [ 1.23934968,  0.6343098 , -1.05846171,  0.1114417 ]])

In [189]:
np.random.ranf(5)

array([0.73755703, 0.6901674 , 0.33374471, 0.97216423, 0.85550732])

In [228]:
np.random.randint(7)

6

5613

In [254]:
np.random.randint(5,20,2)

array([ 8, 18])

###   **Airthmetic Operation In Numpy**

In [265]:
import numpy as np 
var = np.array([1,2,3,4,5,6])
vardd = var + 3
print(vardd)

[4 5 6 7 8 9]


In [269]:
var1 = np.array([1,2,3,4,5,6])
varaible1 = np.array([1,2,3,4,5,6])
vardd1 = var1 + varaible1
print(vardd1)

[ 2  4  6  8 10 12]


In [271]:
import numpy as np 
var = np.array([1,2,3,4,5,6])
vardd = var - 3
print(vardd)

[-2 -1  0  1  2  3]


In [273]:
import numpy as np 
var = np.array([1,2,3,4,5,6])
vardd = var * 3
print(vardd)

[ 3  6  9 12 15 18]


In [275]:
import numpy as np 
var = np.array([1,2,3,4,5,6])
vardd = var / 3
print(vardd)

[0.33333333 0.66666667 1.         1.33333333 1.66666667 2.        ]


In [277]:
import numpy as np 
var = np.array([1,2,3,4,5,6])
vardd = var % 3
print(vardd)

[1 2 0 1 2 0]


In [279]:
import numpy as np 
var = np.array([1,2,3,4,5,6])
vardd = var // 3
print(vardd)

[0 0 1 1 1 2]


## Airthmetic operation 

In [ ]:
np.min
np.max
np.argmin
np.sqrt
np.sin
np.cos
np.cumsum


In [283]:
var = np.array([1,2,3,4,5,6])
print("Max value",max(var))

Max value 6


In [285]:
var = np.array([1,2,3,4,5,6])
print("min value",min(var))

min value 1
