In [1]:
import numpy as np 


In [7]:
np.__version__


'1.26.4'

Creating Arrays 

In [13]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [15]:
type(my_list)

list

In [19]:
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [21]:
type(arr)

numpy.ndarray

In [25]:
np.arange(15)  # --->arange we pass int (pass one args here ) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
np.arange(3.0) 

array([0., 1., 2.])

In [31]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
np.arange(20,10) #(first args is always less than 2 agrs )

array([], dtype=int32)

In [35]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [37]:
np.arange(-16,15) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
        10,  11,  12,  13,  14])

In [39]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [41]:
ar = np.arange(-30,20)
ar 

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [43]:
np.arange(10,10) 

array([], dtype=int32)

In [45]:
np.arange(10,30,5)  # step by 5 

array([10, 15, 20, 25])

In [ ]:
np.zeros(3)  # parameter tunning

In [49]:
np.zeros((2,10 ))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
np.zeros((30,10)) 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [53]:
np.zeros((5,30)) 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
np.ones(3) 

array([1., 1., 1.])

In [57]:
np.ones(4 , dtype = int) 

array([1, 1, 1, 1])

In [59]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [63]:

rand(3,2)
random(3,2)

SyntaxError: invalid syntax (870297111.py, line 2)

In [71]:
np.random.rand(5)

array([0.33943679, 0.17855626, 0.74066234, 0.83130229, 0.4818701 ])

In [73]:
np.random.rand(3,5)

array([[0.40709951, 0.38306592, 0.80084118, 0.15689317, 0.24337128],
       [0.98540799, 0.76003388, 0.58174099, 0.8429879 , 0.42585985],
       [0.41328765, 0.90744902, 0.93077672, 0.91591458, 0.7566768 ]])

In [85]:
np.random.randint(2,4)

2

In [93]:
np.random.randint(20,40)

27

In [95]:
np.random.randint(1,6,4)

array([1, 2, 3, 3])

In [7]:
import numpy as np 
np.random.randint((1,100,12))

array([ 0, 38,  7])

### slicing in matrix 


In [ ]:
import numpy as np 
