## **Introduction to Numpy**

In [1]:

import numpy as np 

In [9]:
np.__version__

'1.26.4'

### **Creating Arrays**

In [16]:
my_list = [1,2,3,4,5]
my_list
type(my_list)

list

In [26]:
l = [1,2,3,4,5]
arr = np.array(l)  # converting list into the array 
arr


array([1, 2, 3, 4, 5])

In [24]:
type(arr) # finding the type of arr =   nd array 


numpy.ndarray

In [28]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [38]:
len(np.arange(-20,10))    # to find the lenth of np.arange

30

In [50]:
np.arange(-16,15)


array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
        10,  11,  12,  13,  14])

In [52]:
len(np.arange(-16,15))


31

In [54]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [56]:
len(ar)

50

In [58]:
np.arange(10,10)

array([], dtype=int32)

In [64]:
 np.arange(10,30,5)  # step by 5 

array([10, 15, 20, 25])

In [68]:
np.zeros(3) # parmeter tunning

array([0., 0., 0.])

In [80]:
np.zeros((5,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [72]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
np.zeros((30,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [82]:
np.ones(3)

array([1., 1., 1.])

In [84]:
np.ones((20,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [94]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [90]:
np.ones(20, dtype = int) # we can pass only 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [96]:
np.two((5,8))

AttributeError: module 'numpy' has no attribute 'two'

In [98]:
rand(3,2)
random(3,2)

NameError: name 'rand' is not defined

In [100]:
np.random.rand(5)

array([0.05715149, 0.84090862, 0.87792908, 0.90139986, 0.42798039])

In [114]:
np.random.rand(4,2)

array([[0.08593726, 0.05050573],
       [0.41526466, 0.15721883],
       [0.68429587, 0.4062616 ],
       [0.30613699, 0.75658246]])

In [130]:
np.random.randint(2,4)

2

In [164]:
np.random.randint(2,8)


6

In [180]:
np.random.randint(1,6,4)

array([5, 5, 5, 4])

In [1]:
import numpy as np 
np.random.randint(-30,20,10)

array([ -6,  -8, -24, -15,  19,  13, -23, -15, -21,  -5])

In [3]:
np.random.randint(1,12,10)

array([1, 9, 4, 1, 8, 7, 2, 8, 7, 4])

In [5]:
np.random.randint(10,40,(10,10))

array([[21, 24, 12, 21, 34, 39, 20, 13, 15, 36],
       [23, 16, 34, 20, 15, 35, 19, 30, 25, 28],
       [36, 13, 20, 31, 11, 28, 28, 25, 27, 27],
       [30, 19, 13, 34, 18, 31, 30, 31, 29, 26],
       [32, 13, 13, 28, 28, 12, 14, 32, 34, 16],
       [35, 38, 10, 31, 22, 33, 21, 14, 29, 38],
       [20, 12, 16, 10, 28, 28, 24, 36, 18, 33],
       [24, 22, 31, 15, 25, 25, 32, 32, 38, 37],
       [38, 35, 38, 10, 26, 24, 15, 24, 38, 29],
       [11, 21, 19, 15, 23, 21, 37, 20, 17, 14]])

In [7]:
np.random.randint(1,100,(12,12))

array([[78, 48, 56, 18, 71,  5, 20, 16, 26, 27, 16, 71],
       [64, 65, 36, 46, 81, 41, 27, 34,  9, 32, 17, 28],
       [75, 81, 61, 53, 84, 14, 10, 92, 11, 92, 88, 79],
       [38,  7, 36, 31,  8, 71, 86, 65, 74, 41, 74,  6],
       [60, 67, 18, 39, 49, 19, 93,  9, 76, 56, 70,  9],
       [89, 39, 46, 69, 27, 19, 90, 57, 17, 35, 94, 56],
       [73, 44, 65, 40,  5, 97, 13, 11, 76, 62, 84, 55],
       [ 4, 81,  5, 12,  8, 64,  6, 65, 56, 72, 55, 62],
       [83, 67, 29, 41, 37, 94, 97, 39, 98, 66, 29, 55],
       [15, 17, 62, 75, 16, 94, 48, 70, 68, 22, 64, 60],
       [56, 60, 66, 66,  3, 24, 74, 56,  5, 62, 89, 16],
       [84, 70, 72, 64,  5, 64, 93,  7, 31,  3, 16, 90]])

In [9]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [19]:
b = np.random.randint(10,20,(5,4))
b

array([[10, 11, 15, 12],
       [10, 15, 10, 19],
       [18, 19, 11, 16],
       [16, 17, 18, 12],
       [16, 17, 15, 15]])

In [21]:
type(b)

numpy.ndarray

In [23]:
b[:]

array([[10, 11, 15, 12],
       [10, 15, 10, 19],
       [18, 19, 11, 16],
       [16, 17, 18, 12],
       [16, 17, 15, 15]])

In [25]:
b[1:3]

array([[10, 15, 10, 19],
       [18, 19, 11, 16]])

In [27]:
b

array([[10, 11, 15, 12],
       [10, 15, 10, 19],
       [18, 19, 11, 16],
       [16, 17, 18, 12],
       [16, 17, 15, 15]])

In [39]:
b[2,3]

16

In [41]:
b[1,-1]

19

In [43]:
b[2:3]

array([[18, 19, 11, 16]])

In [45]:
b[0,-2]

15

In [47]:
b[:]

array([[10, 11, 15, 12],
       [10, 15, 10, 19],
       [18, 19, 11, 16],
       [16, 17, 18, 12],
       [16, 17, 15, 15]])

In [51]:
b[0,2]

15

In [53]:
b[-5:-3]

array([[10, 11, 15, 12],
       [10, 15, 10, 19]])

In [57]:
b[-4,2]

10

In [59]:
b[:]

array([[10, 11, 15, 12],
       [10, 15, 10, 19],
       [18, 19, 11, 16],
       [16, 17, 18, 12],
       [16, 17, 15, 15]])

In [61]:
np.random.randint(10,20,(4,4))

array([[14, 17, 17, 11],
       [11, 19, 13, 15],
       [13, 18, 12, 19],
       [13, 18, 10, 12]])

In [63]:
b

array([[10, 11, 15, 12],
       [10, 15, 10, 19],
       [18, 19, 11, 16],
       [16, 17, 18, 12],
       [16, 17, 15, 15]])

In [65]:
b[-4,-2]

10

In [69]:
b[-4:-2]

array([], shape=(0, 4), dtype=int32)

### Operation

In [75]:
a = np.random.randint(10,20,10)
a

array([14, 13, 19, 18, 17, 11, 10, 18, 10, 18])

In [77]:
id(a)

2707974811312

In [93]:
arr = np.array([0, 1, 2, 3, 4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [85]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[28, 48,  3, 58, 37, 93, 74, 97, 26, 94],
       [37, 24, 60, 75, 97, 35, 90, 69, 65, 36],
       [83, 15, 30,  5, 75, 98, 61, 48,  2, 30],
       [98, 16, 24, 63, 37, 15, 90, 91, 62, 60],
       [10, 52, 86, 33, 20, 86, 44, 88, 33, 30],
       [13, 79, 77, 78, 39, 12, 98, 89, 51, 77],
       [92, 95, 13, 92, 39, 44,  5, 37, 65, 77],
       [47, 60, 89, 42, 79, 28,  4, 35, 89,  7],
       [88, 54, 73,  6, 40, 76, 52, 69,  1, 95],
       [16, 57, 18, 78, 24, 23, 25, 21, 56, 25]])

In [97]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [99]:
arr2

array([[28, 48,  3, 58, 37, 93, 74, 97, 26, 94],
       [37, 24, 60, 75, 97, 35, 90, 69, 65, 36],
       [83, 15, 30,  5, 75, 98, 61, 48,  2, 30],
       [98, 16, 24, 63, 37, 15, 90, 91, 62, 60],
       [10, 52, 86, 33, 20, 86, 44, 88, 33, 30],
       [13, 79, 77, 78, 39, 12, 98, 89, 51, 77],
       [92, 95, 13, 92, 39, 44,  5, 37, 65, 77],
       [47, 60, 89, 42, 79, 28,  4, 35, 89,  7],
       [88, 54, 73,  6, 40, 76, 52, 69,  1, 95],
       [16, 57, 18, 78, 24, 23, 25, 21, 56, 25]])

In [101]:
arr2[-5,5]

12

In [103]:
arr2[-5,-5]

12

In [105]:
arr2

array([[28, 48,  3, 58, 37, 93, 74, 97, 26, 94],
       [37, 24, 60, 75, 97, 35, 90, 69, 65, 36],
       [83, 15, 30,  5, 75, 98, 61, 48,  2, 30],
       [98, 16, 24, 63, 37, 15, 90, 91, 62, 60],
       [10, 52, 86, 33, 20, 86, 44, 88, 33, 30],
       [13, 79, 77, 78, 39, 12, 98, 89, 51, 77],
       [92, 95, 13, 92, 39, 44,  5, 37, 65, 77],
       [47, 60, 89, 42, 79, 28,  4, 35, 89,  7],
       [88, 54, 73,  6, 40, 76, 52, 69,  1, 95],
       [16, 57, 18, 78, 24, 23, 25, 21, 56, 25]])

In [107]:
arr2[-1,-2]

56

In [111]:
arr2[::-1]

array([[16, 57, 18, 78, 24, 23, 25, 21, 56, 25],
       [88, 54, 73,  6, 40, 76, 52, 69,  1, 95],
       [47, 60, 89, 42, 79, 28,  4, 35, 89,  7],
       [92, 95, 13, 92, 39, 44,  5, 37, 65, 77],
       [13, 79, 77, 78, 39, 12, 98, 89, 51, 77],
       [10, 52, 86, 33, 20, 86, 44, 88, 33, 30],
       [98, 16, 24, 63, 37, 15, 90, 91, 62, 60],
       [83, 15, 30,  5, 75, 98, 61, 48,  2, 30],
       [37, 24, 60, 75, 97, 35, 90, 69, 65, 36],
       [28, 48,  3, 58, 37, 93, 74, 97, 26, 94]])

In [113]:
arr2[::-2]

array([[16, 57, 18, 78, 24, 23, 25, 21, 56, 25],
       [47, 60, 89, 42, 79, 28,  4, 35, 89,  7],
       [13, 79, 77, 78, 39, 12, 98, 89, 51, 77],
       [98, 16, 24, 63, 37, 15, 90, 91, 62, 60],
       [37, 24, 60, 75, 97, 35, 90, 69, 65, 36]])

In [119]:
arr2[::-3]

array([[16, 57, 18, 78, 24, 23, 25, 21, 56, 25],
       [92, 95, 13, 92, 39, 44,  5, 37, 65, 77],
       [98, 16, 24, 63, 37, 15, 90, 91, 62, 60],
       [28, 48,  3, 58, 37, 93, 74, 97, 26, 94]])

In [121]:
arr.max()

5

In [123]:
arr2.max()

98

In [125]:
arr.min()

0

In [127]:
arr.mean()

2.5

In [129]:
from numpy import*
a = array([1,2,3,4,9])
median(a)

3.0

In [131]:
arr

array([0, 1, 2, 3, 4, 5])

In [145]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [147]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [155]:
arr.reshape(3,1)

ValueError: cannot reshape array of size 6 into shape (3,1)

## Indexing 

In [160]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [162]:
row = 4
col =5

In [166]:
row


4

In [168]:
col

5

In [170]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
mat[row,col]

45

In [176]:
mat[row,col]

45

In [178]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [182]:
col = 6

In [184]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [186]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [190]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [192]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [205]:
# Python program to genearte otp 
import random 
def geenrate_otp(length = 4) :
    """generate a numeric otp of a specified lenght ."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

otp_length = 4 
otp = geenrate_otp(otp_length)
print(f"Your OTP is : {otp}")


Your OTP is : 3330
